### ISSUE TITLE
Error while parsing command: `pdf@main`

### ISSUE THREAD

**Issue by zhongl** [rizinorg/book#117]
By following [Crackme IOLI_0x01](https://book.rizin.re/src/crackmes/ioli/ioli_0x01.html), i got the error message after input `pdf@main` on my MacBookPro.

The version of **Rizin** is `rizin 0.6.3 @ darwin-arm-64, package: 0.6.3 (Homebrew)`.

I would like create a PR to fix it if this is a typo or outdated.

**Comment by ret2libc** [comment]
Yes it is a typo, it should be `pdf @ main`. In particular, there should be a space between `@` and the address/label you want to go-to.
