### ISSUE TITLE
remove Makefile from plugin dev

### ISSUE THREAD

**Issue by gogo2464** [rizinorg/book#97]
The current book https://book.rizin.re/plugins/dev-asm.html speaks of a Makefile. There is no Makefile anymore in rizin. Only meson.

I suggest to update the documentation.

**Comment by wargio** [comment]
that is need something that needs to be updated.

**Comment by gogo2464** [comment]
Yes @wargio . @ret2libc you could assign me as well if you want. Sounds a good first issue.

**Comment by gogo2464** [comment]
Great!. I was busy. Let me do it right now.
